name: HTML & Link Check

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  proof-html:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Run proof-html
        uses: anishathalye/proof-html@v2
        with:
          directory: ./dist
          check_html: true
          check_css: true
          enforce_https: true
          retries: 3
          timeout: 120
          max_concurrency: 50
          tokens: |
            {"https://github.com": "${{ secrets.GITHUB_TOKEN }}"}
